[package]
name = "demo-usdc-faucet-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.demo-usdc-faucet]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.1"
