// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    loan_refund_escrow_sc
    (
        init => init
        upgrade => upgrade
        depositLoanRepayment => deposit_loan_repayment
        withdrawRepaymentFunds => withdraw_repayment_funds
        getRepaymentFundsBalance => get_repayment_funds_balance
        getProjectId => project_id
        getDeveloperWalletAddress => developer_wallet_address
        getLoanRepaymentTokenId => loan_repayment_token_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
